Repository ripe-tech/ripe-rainbow, pull requests merged in 2020-09, with the labels that each got.

#106 Added Appium driver for mobile testing
  src/ripe_rainbow/domain/base/interactions.py
  src/ripe_rainbow/domain/base/logic.py
  src/ripe_rainbow/interactive/drivers.py
Labels: enhancement, fast-track, p-high

#107 Fix regressions
  src/ripe_rainbow/domain/base/interactions.py
  src/ripe_rainbow/interactive/drivers.py
Labels: bug

#108 Fallback find for AppiumDriver
  src/ripe_rainbow/interactive/drivers.py
Labels: enhancement
